[package]
name = "use_import"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# need rebuild after add each dependencies
# cargo build
[dependencies]
rand = "0.8.3"